@hostname=localhost
@port=4444
@address=http://{{hostname}}:{{port}}

### Get a document by ID.
# Returns an `ExampleDocument`, or `null` if there is no document with the given ID:
# {
#     _id: u32,
#     string: String,
#     number: i32
# }
#
# @prompt id The ID of the document to get

GET {{address}}/read/{{id}}
