@hostname=localhost
@port=4444
@address=http://{{hostname}}:{{port}}

### Insert or update a document (of type `ExampleDocument`).
# Returns HTTP status code only.
#
# @prompt id The ID of the document to insert or update
# @prompt string An arbitrary string to store in the document
# @prompt number An arbitrary 32-bit integer to store in the document

PUT {{address}}/write
Content-Type: application/json

{
	"_id": {{id}},
	"string": "{{string}}",
	"number": {{number}}
}
