@hostname=localhost
@port=4444
@address=http://{{hostname}}:{{port}}

### Get document by ID

GET {{address}}/read/1

### Insert or update document

PUT {{address}}/write
Content-Type: application/json

{
	"_id": 1,
	"string": "Hello world",
	"number": 399
}
