@hostname=localhost
@port=4444
@address=http://{{hostname}}:{{port}}

### Push a user's answers for a form.
# Returns HTTP status code only.
#
# This endpoint takes an array of question-answer pairs; this example request answers exactly one question.
#
# @prompt user_id the ObjectId of the user - TODO once auth is implemented this will be based on the auth header instead
# @prompt form_id the ObjectId of the form to push answers for
# @prompt question_type Multichoice, Slider, or FreeForm
# @prompt question_id The ObjectId of the question being answered
# @prompt answer The answer to the question - of type ObjectId, f64, or String. Include quotes for non-f64 types when running this request manually.

PUT {{address}}/form/push_answers
Content-Type: application/json

{
	"user_id": "{{user_id}}",
	"form_id": "{{form_id}}",
	"answers": [
		{"{{question_type}}": ["{{question_id}}", {{answer}}]}
	]
}
