@hostname=localhost
@port=4444
@address=http://{{hostname}}:{{port}}

### Submit a `Form` associated with a given user.
# On success, returns {created_id: ObjectId}
#
# This endpoint takes an array of questions and answers; three questions are hardcoded here as an example.
#
# @prompt user_id the ObjectId of the user - TODO once auth is implemented this will be based on the auth header instead
# @prompt title the title of the form
# @prompt multichoice_option the selected multi-choice option (either option_1 or option_2)
# @prompt slider_option the selected slider value (from 0 to 10000)
# @prompt freeform_text the text answer for the freeform question

PUT {{address}}/form/submit
Content-Type: application/json

{
	"user_id": "{{user_id}}",
	"title": "{{title}}",
	"responses": [
		{"Multichoice": [{
			"title": "Example multichoice question",
			"options": [
				{"name": "option_1"},
				{"name": "option_2"}
			],
			"min_selected": 1,
			"max_selected": 1
		}, "{{multichoice_option}}"]},
		{"Slider": [{
			"title": "Example slider question",
			"units": "kWh",
			"low": 0,
			"high": 10000,
			"step": 100
		}, {{slider_option}}]},
		{"FreeForm": [{
			"title": "Example freeform question",
			"min_length": 0,
			"max_length": 1000
		}, "{{freeform_text}}"]}
	]
}
