name: check

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: cargo test
        run: cargo test --all-features

      - name: fmt check
        run: cargo fmt --all -- --check

      - name: clippy pedantic check
        run: cargo clippy -- -F clippy::pedantic